USE [master]
GO

/****** Object:  Database [Ordinacija]    Script Date: 3/21/2023 20:46:39 ******/
CREATE DATABASE [Ordinacija]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ordinacija', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Ordinacija.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ordinacija_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Ordinacija_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ordinacija].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Ordinacija] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Ordinacija] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Ordinacija] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Ordinacija] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Ordinacija] SET ARITHABORT OFF 
GO

ALTER DATABASE [Ordinacija] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Ordinacija] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Ordinacija] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Ordinacija] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Ordinacija] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Ordinacija] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Ordinacija] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Ordinacija] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Ordinacija] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Ordinacija] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Ordinacija] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Ordinacija] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Ordinacija] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Ordinacija] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Ordinacija] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Ordinacija] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Ordinacija] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Ordinacija] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Ordinacija] SET  MULTI_USER 
GO

ALTER DATABASE [Ordinacija] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Ordinacija] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Ordinacija] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Ordinacija] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Ordinacija] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Ordinacija] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Ordinacija] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Ordinacija] SET  READ_WRITE 
GO

